version: "3.4"

services:
  docker-discord-logger:
    container_name: docker-discord-logger
    image: ghcr.io/1randomdev/docker-discord-logger:latest
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINERS=Container1:Container2:Container3
      - WEBHOOK_URL=<discord webhook url>
    restart: unless-stopped
